/* ==========  STUDENT SETUP TOKENS  ==========
   Durable one-click setup links for educator-provisioned student accounts, replacing the
   temp-password handover: createStudentAccountAction mints a secret-token row and returns a
   /welcome/[token] URL; the /welcome route (service role, authorized by possession of the
   192-bit secret) mints a fresh short-lived Supabase recovery link at click time and hands
   off to /auth/confirm, landing the student signed-in on /onboarding/set-password. Reusable
   until profiles.must_change_password clears (the natural spent signal) or the row is
   revoked. Hand-authored and idempotent, mirroring supabase/schemas 02_schema / 03_rls (the
   source of truth) in the same style as 20260702100000_class_invites. All writes are
   service-role only — deliberately no authenticated insert/update/delete policies; the
   select policy exists solely for a future issuer-side manage/resend UI. */

CREATE TABLE IF NOT EXISTS public.student_setup_tokens (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    token TEXT NOT NULL UNIQUE DEFAULT encode(extensions.gen_random_bytes(24), 'hex')
        CHECK (char_length(token) BETWEEN 16 AND 128),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE ON UPDATE CASCADE,
    class_id UUID NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL ON UPDATE CASCADE,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
COMMENT ON TABLE public.student_setup_tokens IS 'Durable one-click setup links for educator-provisioned student accounts. createStudentAccountAction mints a row (service role) and hands the educator a /welcome/[token] URL; the /welcome route (service role, authorized by possession of the 192-bit secret in the URL) resolves the row, mints a FRESH short-lived Supabase recovery link at click time, and hands off to /auth/confirm, landing the student signed-in on /onboarding/set-password. Deliberately reusable until profiles.must_change_password flips FALSE (the natural spent signal — a student who bails mid-flow can re-click) or the row is revoked. Students never read this table; the only authenticated surface is the issuer/admin select for a future manage or resend UI.';
COMMENT ON COLUMN public.student_setup_tokens.token IS 'The setup secret: 24 random bytes hex-encoded (48 chars, 192 bits) generated by the DB default, same recipe as class_invites.token. The create action inserts and reads it back via RETURNING token; possession of it is what authorizes the /welcome route''s service-role handoff.';
COMMENT ON COLUMN public.student_setup_tokens.user_id IS 'The provisioned student account this link signs in. Cascade-deleted with the profile, so a deleted account can never be resurrected through a stale link.';
COMMENT ON COLUMN public.student_setup_tokens.created_by IS 'Issuer bookkeeping (the educator or admin who provisioned the account); ON DELETE SET NULL because the link must keep working for the student even if the issuing account goes away.';
COMMENT ON COLUMN public.student_setup_tokens.revoked_at IS 'Manual kill switch for a mis-sent link (service-role or admin write; no UI yet). The everyday expiry is NOT this column — it is profiles.must_change_password flipping FALSE once the student sets their own password.';

CREATE INDEX IF NOT EXISTS idx_student_setup_tokens_user_id ON public.student_setup_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_student_setup_tokens_class_id ON public.student_setup_tokens(class_id);
CREATE INDEX IF NOT EXISTS idx_student_setup_tokens_created_by ON public.student_setup_tokens(created_by);

DROP TRIGGER IF EXISTS enforce_immutability_student_setup_tokens ON public.student_setup_tokens;
CREATE TRIGGER enforce_immutability_student_setup_tokens
    BEFORE UPDATE ON public.student_setup_tokens
    FOR EACH ROW EXECUTE PROCEDURE internal.prevent_immutable_modifications();

ALTER TABLE public.student_setup_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_setup_tokens FORCE ROW LEVEL SECURITY;

/* Every write is service-role only (createStudentAccountAction mints the row; the /welcome route reads
   it with the admin client, authorized by possession of the secret) — deliberately NO insert/update/
   delete policies for authenticated, mirroring how class_invites keeps its secret handling out of
   client reach. The select policy exists solely for a future issuer-side manage/resend UI; students
   never read this table. */
DROP POLICY IF EXISTS student_setup_tokens_select_issuer_or_admin ON public.student_setup_tokens;
CREATE POLICY student_setup_tokens_select_issuer_or_admin ON public.student_setup_tokens
    FOR SELECT TO authenticated
    USING (
        (SELECT internal.is_admin())
        OR created_by = (SELECT auth.uid())
    );
COMMENT ON POLICY student_setup_tokens_select_issuer_or_admin ON public.student_setup_tokens IS 'Issuer-or-admin read for a future manage/resend surface. All writes stay service-role only: RLS blocks authenticated INSERT/UPDATE/DELETE entirely, so the secret lifecycle is owned by createStudentAccountAction and the /welcome route.';
