/* ==========  CLASS INVITES  ==========
   Single-use invite-link enrollment for the manual-payment (bank transfer) onboarding flow.
   Adds the class_invites table + indexes + triggers, RLS (owner-or-admin only), and the two
   public RPCs: get_class_invite_preview (anon-callable landing-page read) and
   redeem_class_invite (authenticated single-use enrollment writer). Hand-authored and
   idempotent, mirroring supabase/schemas 01_functions / 02_schema / 03_rls (the source of
   truth) — db diff is unreliable here because the RPCs forward-reference class_invites.
   See plans/invite-link-enrollment.md.

   The immutability trigger locks only id + created_at (the existing generic
   internal.prevent_immutable_modifications). That is sufficient: RLS confines an educator
   UPDATE to invites of classes they teach, and there is deliberately no redeemed_* anti-spoof
   guard — the worst a malicious educator could do is mark/unmark their own invite, which
   grants no unauthorized access (enrollment is a separate RPC-gated write). */

CREATE TABLE IF NOT EXISTS public.class_invites (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    token TEXT NOT NULL UNIQUE DEFAULT encode(extensions.gen_random_bytes(24), 'hex')
        CHECK (char_length(token) BETWEEN 16 AND 128),
    class_id UUID NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL ON UPDATE CASCADE,
    email TEXT CHECK (email IS NULL OR char_length(email) <= 255),
    note TEXT CHECK (note IS NULL OR char_length(note) <= 200),
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    redeemed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL ON UPDATE CASCADE,
    redeemed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
COMMENT ON TABLE public.class_invites IS 'Single-use, per-student invite links for manual (off-platform payment) enrollment. An educator or admin generates a secret token URL for one class and hands it to the student manually; the student redeems it via the redeem_class_invite RPC, which enrols them bypassing the marketplace. Optional email binding, optional expiry, revocable via revoked_at. Students never touch this table directly — the anon-callable get_class_invite_preview RPC and the authenticated redeem_class_invite RPC are the only student-facing surfaces.';
COMMENT ON COLUMN public.class_invites.token IS 'The invite secret: 24 random bytes hex-encoded (48 chars, 192 bits) generated by the DB default. Mirrors the classes.code gen_random_bytes pattern but secret-grade and non-enumerable. The create action inserts and reads it back via RETURNING token.';
COMMENT ON COLUMN public.class_invites.email IS 'Optional binding to the invitee''s email, stored lowercased by the action. NULL means anyone holding the link may redeem it — the default expectation for a manually shared secret link.';
COMMENT ON COLUMN public.class_invites.created_by IS 'ON DELETE SET NULL is non-essential bookkeeping: deleting an educator account deletes their classes first (deleteEducatorAccountAction), which cascades the invites away before the profile row goes.';
COMMENT ON COLUMN public.class_invites.redeemed_at IS 'Single-use marker. redeemed_by / redeemed_at are written only by the redeem_class_invite RPC; set means the invite is spent (idempotent for the same redeemer, rejected for anyone else).';

CREATE INDEX IF NOT EXISTS idx_class_invites_class_id ON public.class_invites(class_id);
CREATE INDEX IF NOT EXISTS idx_class_invites_created_by ON public.class_invites(created_by);
CREATE INDEX IF NOT EXISTS idx_class_invites_redeemed_by ON public.class_invites(redeemed_by);

DROP TRIGGER IF EXISTS set_class_invites_updated_at ON public.class_invites;
CREATE TRIGGER set_class_invites_updated_at
    BEFORE UPDATE ON public.class_invites
    FOR EACH ROW EXECUTE PROCEDURE internal.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS enforce_immutability_class_invites ON public.class_invites;
CREATE TRIGGER enforce_immutability_class_invites
    BEFORE UPDATE ON public.class_invites
    FOR EACH ROW EXECUTE PROCEDURE internal.prevent_immutable_modifications();

ALTER TABLE public.class_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_invites FORCE ROW LEVEL SECURITY;

/* Educators see/manage invites for classes they teach; admins see all. Students NEVER read this table
   directly — they go through the SECURITY DEFINER preview/redeem RPCs. */
DROP POLICY IF EXISTS class_invites_select_owner_or_admin ON public.class_invites;
CREATE POLICY class_invites_select_owner_or_admin ON public.class_invites
    FOR SELECT TO authenticated
    USING (
        (SELECT internal.is_admin())
        OR (SELECT internal.is_class_educator(class_id))
        OR created_by = (SELECT auth.uid())
    );
COMMENT ON POLICY class_invites_select_owner_or_admin ON public.class_invites IS 'Owner-or-admin read of the invite ledger. The created_by branch keeps an issuer''s rows visible even if class ownership ever moves; students hit the SECURITY DEFINER RPCs instead, never this table.';

DROP POLICY IF EXISTS class_invites_insert_owner_or_admin ON public.class_invites;
CREATE POLICY class_invites_insert_owner_or_admin ON public.class_invites
    FOR INSERT TO authenticated
    WITH CHECK (
        created_by = (SELECT auth.uid())
        AND ((SELECT internal.is_admin()) OR (SELECT internal.is_class_educator(class_id)))
    );
COMMENT ON POLICY class_invites_insert_owner_or_admin ON public.class_invites IS 'Only the educator of the target class or an admin may mint an invite, and the issuer must stamp themselves as created_by.';

DROP POLICY IF EXISTS class_invites_update_owner_or_admin ON public.class_invites;
CREATE POLICY class_invites_update_owner_or_admin ON public.class_invites
    FOR UPDATE TO authenticated
    USING ((SELECT internal.is_admin()) OR (SELECT internal.is_class_educator(class_id)))
    WITH CHECK ((SELECT internal.is_admin()) OR (SELECT internal.is_class_educator(class_id)));
COMMENT ON POLICY class_invites_update_owner_or_admin ON public.class_invites IS 'Class educator or admin may mutate their own class''s invites — the only UI-exposed mutation is revoke (revoked_at). No redeemed_* anti-spoof trigger by design: the worst an educator can do is mark/unmark their own invite, which grants no unauthorized access (enrollment is a separate RPC-gated write).';

DROP POLICY IF EXISTS class_invites_delete_owner_or_admin ON public.class_invites;
CREATE POLICY class_invites_delete_owner_or_admin ON public.class_invites
    FOR DELETE TO authenticated
    USING ((SELECT internal.is_admin()) OR (SELECT internal.is_class_educator(class_id)));
COMMENT ON POLICY class_invites_delete_owner_or_admin ON public.class_invites IS 'Class educator or admin may hard-delete an invite (housekeeping); redeemed enrollments are unaffected — the enrollment row lives in class_enrollments.';

CREATE OR REPLACE FUNCTION public.get_class_invite_preview(p_token TEXT)
RETURNS TABLE (class_id UUID, class_title TEXT, educator_name TEXT, redeemable BOOLEAN, reason TEXT)
AS $$
BEGIN
    RETURN QUERY
    SELECT
        c.id,
        c.title,
        COALESCE(NULLIF(TRIM(COALESCE(pp.display_name, CONCAT_WS(' ', pp.first_name, pp.last_name))), ''), 'An educator'),
        (ci.revoked_at IS NULL
            AND ci.redeemed_at IS NULL
            AND (ci.expires_at IS NULL OR ci.expires_at > NOW())),
        CASE
            WHEN ci.revoked_at IS NOT NULL THEN 'revoked'
            WHEN ci.redeemed_at IS NOT NULL THEN 'redeemed'
            WHEN ci.expires_at IS NOT NULL AND ci.expires_at <= NOW() THEN 'expired'
            ELSE 'valid'
        END
    FROM public.class_invites ci
    JOIN public.classes c ON c.id = ci.class_id
    LEFT JOIN public.profiles_public pp ON pp.id = c.educator_id
    WHERE ci.token = p_token;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';
COMMENT ON FUNCTION public.get_class_invite_preview(TEXT) IS 'Public (anon-callable) read boundary for the invite landing page: given the secret token, returns the class title, the educator''s display name, and whether the invite is still redeemable (with a reason of revoked / redeemed / expired / valid). Leaks nothing beyond the title + name — never email, note, or issuer — and returns zero rows for unknown tokens, so there is no existence oracle without holding the 192-bit secret. SECURITY DEFINER with empty search_path; the WHERE clause and column list ARE the boundary, following the get_public_educator_profile pattern.';

REVOKE EXECUTE ON FUNCTION public.get_class_invite_preview(TEXT) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.get_class_invite_preview(TEXT) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.redeem_class_invite(p_token TEXT)
RETURNS UUID AS $$
DECLARE
    v_uid       UUID := (SELECT auth.uid());
    v_invite    public.class_invites%ROWTYPE;
    v_educator  UUID;
    v_caller_email TEXT;
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'AUTH REQUIRED: Sign in to accept this invite.';
    END IF;

    SELECT * INTO v_invite FROM public.class_invites WHERE token = p_token FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'This invite link is not valid.';
    END IF;
    IF v_invite.revoked_at IS NOT NULL THEN
        RAISE EXCEPTION 'This invite has been revoked.';
    END IF;
    IF v_invite.expires_at IS NOT NULL AND v_invite.expires_at <= NOW() THEN
        RAISE EXCEPTION 'This invite has expired.';
    END IF;

    /* Idempotent: the same user re-opening their already-redeemed link just lands in the class. */
    IF v_invite.redeemed_at IS NOT NULL THEN
        IF v_invite.redeemed_by = v_uid THEN
            INSERT INTO public.class_enrollments (user_id, class_id)
            VALUES (v_uid, v_invite.class_id) ON CONFLICT (user_id, class_id) DO NOTHING;
            RETURN v_invite.class_id;
        END IF;
        RAISE EXCEPTION 'This invite has already been used.';
    END IF;

    /* Optional email binding. */
    IF v_invite.email IS NOT NULL THEN
        SELECT email INTO v_caller_email FROM auth.users WHERE id = v_uid;
        IF LOWER(v_caller_email) IS DISTINCT FROM LOWER(v_invite.email) THEN
            RAISE EXCEPTION 'This invite was issued for a different email address.';
        END IF;
    END IF;

    SELECT educator_id INTO v_educator FROM public.classes WHERE id = v_invite.class_id;
    IF v_educator = v_uid THEN
        RAISE EXCEPTION 'You teach this class — you cannot enrol as a student.';
    END IF;

    INSERT INTO public.class_enrollments (user_id, class_id)
    VALUES (v_uid, v_invite.class_id) ON CONFLICT (user_id, class_id) DO NOTHING;

    UPDATE public.class_invites
    SET redeemed_by = v_uid, redeemed_at = NOW()
    WHERE id = v_invite.id;

    RETURN v_invite.class_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';
COMMENT ON FUNCTION public.redeem_class_invite(TEXT) IS 'The manual-payment enrollment writer. Validates the secret invite token (exists, not revoked, not expired), enforces single use (idempotent for the same caller — re-opening a redeemed link just re-lands them in the class; anyone else is rejected), honors the optional email binding against auth.users, and blocks the class educator from self-enrolling, then inserts the class_enrollments row and stamps redeemed_by / redeemed_at. SECURITY DEFINER bypasses the admin/educator-only insert policy on class_enrollments, exactly like enroll_in_free_class. Deliberately does NOT require is_published or price_cents = 0 — the invite is an explicit grant for an externally-paid (possibly draft) class. SELECT ... FOR UPDATE locks the invite row so two concurrent redeems cannot both win the single use. Returns the class_id for the post-join redirect.';

REVOKE EXECUTE ON FUNCTION public.redeem_class_invite(TEXT) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.redeem_class_invite(TEXT) TO authenticated;
